name: release MCDRCommandCompleterReforged
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Setup Python 3.10
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mcdreforged -U

      - name: Build MCDR Plugin
        run: |
          mcdreforged pack

      - name: Find correct plugin
        id: find_plugin
        run: |
          output="$(find ./ -name "*.mcdr" -type f -printf "%f\n")"
          echo "plugin_name=$output" >> $GITHUB_OUTPUT

      - name: capture build artifacts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: ${{ steps.find_plugin.outputs.plugin_name }}
          path: ./${{ steps.find_plugin.outputs.plugin_name }}

      - name: publish
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ./${{ steps.find_plugin.outputs.plugin_name }}
